### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by breningham** [SIMPATICOProject/CPD#9]
Hi Just tried running this in a docker-compose environment, with a custom Dockerfile.

But the Application is currently unable to be built as it cannot find `it.beng.microservice.common.ServerError` (cannot find symbol)

```[INFO] Changes detected - recompiling the module!
[INFO] Compiling 43 source files to /build/target/classes
[INFO] /build/src/main/java/it/beng/modeler/config.java: /build/src/main/java/it/beng/modeler/config.java uses unchecked or unsafe operations.
[INFO] /build/src/main/java/it/beng/modeler/config.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/auth/OAuth2ImplicitSubRoute.java:[17,35] cannot find symbol
  symbol:   class ServerError
  location: package it.beng.microservice.common
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/AuthSubRoute.java:[13,35] cannot find symbol
  symbol:   class ServerError
  location: package it.beng.microservice.common
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/SchemaSubRoute.java:[13,35] cannot find symbol
  symbol:   class ServerError
  location: package it.beng.microservice.common
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/auth/LocalAuthSubRoute.java:[10,35] cannot find symbol
  symbol:   class ServerError
  location: package it.beng.microservice.common
[ERROR] /build/src/main/java/it/beng/modeler/microservice/http/JsonResponse.java:[8,35] cannot find symbol
  symbol:   class ServerError
  location: package it.beng.microservice.common
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/ApiSubRoute.java:[17,35] cannot find symbol
  symbol:   class ServerError
  location: package it.beng.microservice.common
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/auth/OAuth2ImplicitSubRoute.java:[127,40] cannot find symbol
  symbol:   variable ServerError
  location: class it.beng.modeler.microservice.subroute.auth.OAuth2ImplicitSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/AuthSubRoute.java:[44,19] cannot find symbol
  symbol:   variable ServerError
  location: class it.beng.modeler.microservice.subroute.AuthSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/SchemaSubRoute.java:[166,26] cannot find symbol
  symbol:   variable ServerError
  location: class it.beng.modeler.microservice.subroute.SchemaSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/SchemaSubRoute.java:[189,26] cannot find symbol
  symbol:   variable ServerError
  location: class it.beng.modeler.microservice.subroute.SchemaSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/SchemaSubRoute.java:[195,22] cannot find symbol
  symbol:   variable ServerError
  location: class it.beng.modeler.microservice.subroute.SchemaSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/auth/LocalAuthSubRoute.java:[68,30] cannot find symbol
  symbol:   variable ServerError
  location: class it.beng.modeler.microservice.subroute.auth.LocalAuthSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/http/JsonResponse.java:[87,32] cannot find symbol
  symbol:   class ServerError
  location: class it.beng.modeler.microservice.http.JsonResponse
[ERROR] /build/src/main/java/it/beng/modeler/microservice/http/JsonResponse.java:[88,36] cannot find symbol
  symbol:   class ServerError
  location: class it.beng.modeler.microservice.http.JsonResponse
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/ApiSubRoute.java:[262,23] cannot find symbol
  symbol:   variable ServerError
  location: class it.beng.modeler.microservice.subroute.ApiSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/ApiSubRoute.java:[291,30] cannot find symbol
  symbol:   variable ServerError
  location: class it.beng.modeler.microservice.subroute.ApiSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/ApiSubRoute.java:[297,30] cannot find symbol
  symbol:   variable ServerError
  location: class it.beng.modeler.microservice.subroute.ApiSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/ApiSubRoute.java:[302,30] cannot find symbol
  symbol:   variable ServerError
  location: class it.beng.modeler.microservice.subroute.ApiSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/ApiSubRoute.java:[307,30] cannot find symbol
  symbol:   variable ServerError
  location: class it.beng.modeler.microservice.subroute.ApiSubRoute
[INFO] 19 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.628 s
[INFO] Finished at: 2018-07-25T11:52:45Z
[INFO] Final Memory: 30M/787M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project cpd-server: Compilation failure: Compilation failure:
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/auth/OAuth2ImplicitSubRoute.java:[17,35] cannot find symbol
[ERROR]   symbol:   class ServerError
[ERROR]   location: package it.beng.microservice.common
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/AuthSubRoute.java:[13,35] cannot find symbol
[ERROR]   symbol:   class ServerError
[ERROR]   location: package it.beng.microservice.common
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/SchemaSubRoute.java:[13,35] cannot find symbol
[ERROR]   symbol:   class ServerError
[ERROR]   location: package it.beng.microservice.common
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/auth/LocalAuthSubRoute.java:[10,35] cannot find symbol
[ERROR]   symbol:   class ServerError
[ERROR]   location: package it.beng.microservice.common
[ERROR] /build/src/main/java/it/beng/modeler/microservice/http/JsonResponse.java:[8,35] cannot find symbol
[ERROR]   symbol:   class ServerError
[ERROR]   location: package it.beng.microservice.common
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/ApiSubRoute.java:[17,35] cannot find symbol
[ERROR]   symbol:   class ServerError
[ERROR]   location: package it.beng.microservice.common
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/auth/OAuth2ImplicitSubRoute.java:[127,40] cannot find symbol
[ERROR]   symbol:   variable ServerError
[ERROR]   location: class it.beng.modeler.microservice.subroute.auth.OAuth2ImplicitSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/AuthSubRoute.java:[44,19] cannot find symbol
[ERROR]   symbol:   variable ServerError
[ERROR]   location: class it.beng.modeler.microservice.subroute.AuthSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/SchemaSubRoute.java:[166,26] cannot find symbol
[ERROR]   symbol:   variable ServerError
[ERROR]   location: class it.beng.modeler.microservice.subroute.SchemaSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/SchemaSubRoute.java:[189,26] cannot find symbol
[ERROR]   symbol:   variable ServerError
[ERROR]   location: class it.beng.modeler.microservice.subroute.SchemaSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/SchemaSubRoute.java:[195,22] cannot find symbol
[ERROR]   symbol:   variable ServerError
[ERROR]   location: class it.beng.modeler.microservice.subroute.SchemaSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/auth/LocalAuthSubRoute.java:[68,30] cannot find symbol
[ERROR]   symbol:   variable ServerError
[ERROR]   location: class it.beng.modeler.microservice.subroute.auth.LocalAuthSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/http/JsonResponse.java:[87,32] cannot find symbol
[ERROR]   symbol:   class ServerError
[ERROR]   location: class it.beng.modeler.microservice.http.JsonResponse
[ERROR] /build/src/main/java/it/beng/modeler/microservice/http/JsonResponse.java:[88,36] cannot find symbol
[ERROR]   symbol:   class ServerError
[ERROR]   location: class it.beng.modeler.microservice.http.JsonResponse
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/ApiSubRoute.java:[262,23] cannot find symbol
[ERROR]   symbol:   variable ServerError
[ERROR]   location: class it.beng.modeler.microservice.subroute.ApiSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/ApiSubRoute.java:[291,30] cannot find symbol
[ERROR]   symbol:   variable ServerError
[ERROR]   location: class it.beng.modeler.microservice.subroute.ApiSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/ApiSubRoute.java:[297,30] cannot find symbol
[ERROR]   symbol:   variable ServerError
[ERROR]   location: class it.beng.modeler.microservice.subroute.ApiSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/ApiSubRoute.java:[302,30] cannot find symbol
[ERROR]   symbol:   variable ServerError
[ERROR]   location: class it.beng.modeler.microservice.subroute.ApiSubRoute
[ERROR] /build/src/main/java/it/beng/modeler/microservice/subroute/ApiSubRoute.java:[307,30] cannot find symbol
[ERROR]   symbol:   variable ServerError
[ERROR]   location: class it.beng.modeler.microservice.subroute.ApiSubRoute
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project cpd-server: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1029)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:137)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more```

During testing it seems that the Dockerfile provided ALSO errors.

**Comment by vcartelli** [comment]
Yes, the project was pointing to a wrong dependency version.
This should be fixed now. Can you please confirm it?
